
#cambiar el logo de springboot por uno propio (configuraciones en spring apendix)
spring:
  banner:
    location:  classpath:banner.txt #classpath/folder/banner.txt
    
  main:
    allow-bean-definition-overriding: true
    
#Nombre de la aplicación
  application.name: reserpadel
#Configuración de la bbdd
  datasource:
    url: jdbc:mariadb://localhost:3306/reserpadel
    username: root
    password: root
# esto se carga la bdd cuando inicia srping
#  jpa.hibernate.ddl-auto: create

  
#Constantes
exceptions:
  email: Email no informado o erroneo
  user:
    notfound: Persona no encontrada
    exist: ya esta registrado
  floor:
    duplicate: está duplicada.
    noexist: no existe.
    nofill: Pista no informada.
    
